### ISSUE TITLE
Refactor the configuration to feature provider as a global service

### ISSUE THREAD

**Issue by falexandrou** [stackmate-io/engine#1019]
At the moment, we have separate `provider` and `region` entries in the project's configuration file.

We can transform this into an object to work as follows:

```yaml
providers:
  aws:
    region: eu-central-1
   # ... other options from the aws provider here
```

We can then merge this configuration when we normalize the project
